on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v3
      - run: nimble install -y
      - run: nimble test
      - run: nimble test --gc:arc
      - run: nimble buildexamples
      - run: nimble gendoc
